name: test
on: push
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-gradle@main
      - run: gradle test
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-gradle@main
      - run: ./scripts/gradle.sh version

