name: test
on: push
jobs:
  liberica:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: gradle build
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ./scripts/install.sh # TODO

