on: push
jobs:
    liberica:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: '21'
              distribution: 'liberica'
        